apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosmemottakmock
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmemottakmock"
  image: "repo.adeo.no:5443/syfo/syfosmemottakmock:@@VERSION@@"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - "https://syfosmemottakmock.nais.preprod.local"